# This file gathers the routes and the rights required to access each of them
# This file is called by the ControllerAuthorization Listener

"ajax.editabsencereasons":
    - 100
"ajax.holidaydelete":
    - 100
"ajax.changepassword":
    - 21
"ajax.planningjobcheckcopy":
    - 100
"ajax.mailtest":
    - 100
"ajax.holidaycredit":
    - 100
"framework.index":
    - 22
"statistics.index":
    - 17
"statistics.time":
    - 17
"workinghour.index":
    - 1101
"workinghour.add":
    - 100
"workinghour.edit":
    - 100
"workinghour.save":
    - 100
"workinghour.delete":
    - 1101
