# This file gathers the routes and the rights required to access each of them
# This file is called by the ControllerAuthorization Listener

"absence.add":
    - 100
"absence.delete":
    - 100
"absence.edit":
    - 100
"absence.index":
    - 100
"absence.save":
    - 100
"absences.document.index":
    - 100
"absences.document.delete":
    - 100
"absences.document.add":
    - 100
"absences.document.list":
    - 100
"account.index":
    - 100
"admin.index":
    - 100
"agent.index":
    - 4
"ajax.agentsites":
    - 100
"ajax.agentsbysites":
    - 100
"ajax.checkplanning":
    - 100
"ajax.currentcredits":
    - 100
"ajax.editabsencereasons":
    - 100
"ajax.holidaycredit":
    - 100
"ajax.holidaydelete":
    - 100
"ajax.holidays-hours-to-days":
    - 100
"ajax.holiday.absence.control":
    - 100
"ajax.changepassword":
    - 21
"ajax.planningjobcheckcopy":
    - 100
"ajax.mailtest":
    - 100
"ajax.update_agent_login":
    - 21
"comp-time.index":
    - 100
"ajax.workinghourtables":
    - 100
"framework.index":
    - 22
"framework.add_table":
    - 22
"framework.edit_table":
    - 22
"framework.save_table":
    - 22
"framework.save_table_info":
    - 22
"framework.save_table_line":
    - 22
"framework.delete_table":
    - 22
"framework.delete_selected_tables":
    - 22
"framework.restore_table":
    - 22
"framework.add_group":
    - 22
"framework.edit_group":
    - 22
"framework.save_group":
    - 22
"framework.delete_group":
    - 22
"framework.delete_line":
    - 22
"framework.add_line":
    - 22
"framework.edit_line":
    - 22
"framework.save_line":
    - 22
"framework.copy_table":
    - 22
"notification.index":
    - 21
"notification.save":
    - 21
"model.index":
    - 301
"model.save":
    - 301
"model.edit":
    - 301
"model.delete":
    - 301
"planningjob.contextmenu":
    - 100
"interchange.agents":
    - 100
"interchange.slots":
    - 100
"statedweek.gethours":
    - 1401
"statedweek.sethours":
    - 1401
"statedweek.availables":
    - 1401
"statedweek.placed":
    - 100
"statedweek.add":
    - 1401
"statedweek.slothours":
    - 1401
"statedweekjob.add":
    - 1401
"statedweekpause.add":
    - 1401
"statedweekjob.update":
    - 1401
"statedweek.remove":
    - 1401
"statedweekjob.remove":
    - 1401
"statedweekpause.remove":
    - 1401
"statedweek.lock":
    - 1401
"statedweek.empty":
    - 1401
"statedweek.template.load":
    - 1401
"statedweek.template.add":
    - 1401
"statistics.absence":
    - 17
"statistics.agent":
    - 17
"statistics.index":
    - 17
"statistics.positionsummary":
    - 17
"statistics.saturday":
    - 17
"statistics.service":
    - 17
"statistics.status":
    - 17
"statistics.supportposition":
    - 17
"statistics.time":
    - 17
"workinghour.index":
    - 1101
    - 1201
"workinghour.add":
    - 100
"workinghour.edit":
    - 100
"workinghour.save":
    - 100
"workinghour.delete":
    - 1101
    - 1201
