# This file gathers the routes and the rights required to access each of them
# This file is called by the ControllerAuthorization Listener

"account.index":
    - 100
"agent.index":
    - 4
"ajax.editabsencereasons":
    - 100
"ajax.holidaycredit":
    - 100
"ajax.holidaydelete":
    - 100
"ajax.holiday-halfday-hours":
    - 100
"ajax.holidays-hours-to-days":
    - 100
"ajax.changepassword":
    - 21
"ajax.planningjobcheckcopy":
    - 100
"ajax.mailtest":
    - 100
"comp-time.index":
    - 100
"framework.index":
    - 22
"framework.add_table":
    - 22
"framework.edit_table":
    - 22
"framework.save_table":
    - 22
"framework.save_table_info":
    - 22
"framework.save_table_line":
    - 22
"framework.delete_table":
    - 22
"framework.delete_selected_tables":
    - 22
"framework.restore_table":
    - 22
"framework.add_group":
    - 22
"framework.edit_group":
    - 22
"framework.save_group":
    - 22
"framework.delete_group":
    - 22
"framework.delete_line":
    - 22
"framework.add_line":
    - 22
"framework.edit_line":
    - 22
"framework.save_line":
    - 22
"framework.copy_table":
    - 22
"notification.index":
    - 21
"notification.save":
    - 21
"model.index":
    - 301
"model.save":
    - 301
"model.edit":
    - 301
"model.delete":
    - 301
"statistics.absence":
    - 17
"statistics.agent":
    - 17
"statistics.index":
    - 17
"statistics.positionsummary":
    - 17
"statistics.saturday":
    - 17
"statistics.service":
    - 17
"statistics.status":
    - 17
"statistics.supportposition":
    - 17
"statistics.time":
    - 17
"workinghour.index":
    - 1101
    - 1201
"workinghour.add":
    - 100
"workinghour.edit":
    - 100
"workinghour.save":
    - 100
"ajax.holiday.absence.control":
    - 100
"workinghour.delete":
    - 1101
    - 1201
